%YAML 1.2
---

resources_dir: "/resources/current_setups"
setup_dir: "default"

zkey_filename: "prover_key.zkey"
witness_gen_binary_filename: "main_c"
test_verification_key_filename: "verification_key.json"
oidc_providers:
  - iss: "https://accounts.google.com"
    endpoint_url: "https://www.googleapis.com/oauth2/v3/certs"
jwk_refresh_rate_secs: 10
port: 8080
metrics_port: 9100
enable_dangerous_logging: false
enable_debug_checks: false
enable_federated_jwks: false
enable_jwt_exp_not_in_the_past_check: true
enable_jwt_iat_not_in_future_check: true
